apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: artifact-repo-1-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: s3-access
subjects:
  - kind: ServiceAccount
    name: artifact-repo-1-access
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: artifact-repo-2-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: s3-access
subjects:
  - kind: ServiceAccount
    name: artifact-repo-2-access
    namespace: {{ .Release.Namespace }}
