apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-workflow
  namespace: {{ .Release.Namespace }}
spec:
  entrypoint: hello
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{ `{{inputs.parameters.message}}` }}"]

  - name: hello
    dag:
      tasks:
      - name: A
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello A"}]
      - name: B
        dependencies: [A]
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello B"}]
      - name: C
        dependencies: [A]
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello C"}]
      - name: D
        dependencies: [B, C]
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello D"}]
