releases:
  - name: argo-workflows
    namespace: argo-workflows
    forceNamespace: argo-workflows
    chart: argo/argo-workflows
    version: 0.33.3
    values: 
      - argoworkflows.yaml

  - name: workflows
    chart: workflows
    namespace: argo-workflows
    version: 0.1.0
