releases:
  - name: argo-workflows
    namespace: argo-workflows
    forceNamespace: argo-workflows
    chart: argo/argo-workflows
    version: 0.33.3
    values: 
      - argoworkflows.yaml.gotmpl

  - name: workflows
    chart: workflows
    namespace: argo-workflows
    version: 0.1.0
    values:
      - s3_1_access_role_arn: {{ requiredEnv "S3_1_ACCESS_ROLE_ARN" }}
      - s3_2_access_role_arn: {{ requiredEnv "S3_2_ACCESS_ROLE_ARN" }}
